version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/Difficalcy.PerformancePlus"
      - "/Difficalcy.PerformancePlus.Tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
