services:
  difficalcy-performanceplus:
    build:
      context: .
      target: difficalcy-performanceplus
      args:
        - OSU_COMMIT_HASH
    environment:
      - REDIS_CONFIGURATION=cache:6379
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${beatmap_path}:/beatmaps
    depends_on:
      - cache

  cache:
    image: redis:7
    volumes:
      - redis-data:/data

  docs:
    build: ./docs
    volumes:
      - ./docs:/docs

volumes:
  redis-data:
