services:
  difficalcy-performanceplus:
    build:
      context: .
      target: difficalcy-performanceplus
      args:
        OSU_COMMIT_HASH: e6fc95d77047d18ae7f2c3f3571d66f091938c37
    environment:
      - REDIS_CONFIGURATION=cache:6379
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./beatmaps:/beatmaps
    depends_on:
      - cache

  cache:
    image: redis:7
    volumes:
      - redis-data:/data

  docs:
    build: ./docs
    volumes:
      - ./docs:/docs

volumes:
  redis-data:
